# .travis.yml
#
# Travis CI configuration file


# The Ubuntu 22.04 (Jammy Jellyfish) Build Environment
dist: jammy

language: python

# Safelist
branches:
  only:
    - main

# Supported Python versions: https://devguide.python.org/versions/
matrix:
  include:
    - python: 3.8
    - python: 3.9
    - python: 3.10
    - python: 3.11
    - python: 3.12    # Current stable release for python
#    - python: 3.13    # Prerelease
#    - python: 3.14    # Feature
#    - python: "nightly"    # Nightly build

# Commands to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

# Command to run tests
script:
  - pytest
  - coverage run -m pc_health_checks

after_success:
  - coveralls
  - codecov

after_failure:
  echo "This is a failure! ";
