language: python

# os: osx

python:
  - 3.8
  - 3.9
#  - 3.10
#  - 3.11
#  - 3.12    # Current stable release for python
#  - 3.13    # Prerelease
#  - 3.14    # feature
  - "nightly"    # Nightly build

# Command to install dependencies
install:
# install: skip
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

# Command to run tests
# script: skip
script:
  - pytest

after_success:
  - coveralls
  - codecov

after_failure:
  echo "This is a failure! ";
